### ISSUE TITLE
How do you make a colon ":"?

### ISSUE THREAD

**Issue by npx** [caksoylar/zmk-config#1]
Stumbled across your layout and was wondering :)
Is it due to your language setting that you will shift the . to make it :?

**Comment by caksoylar** [comment]
Hey, I use the US English layout so <kbd>shift</kbd> + <kbd>;</kbd> = <kbd>:</kbd>. I usually use the <kbd>;</kbd> that is a combo on U and I keys on QWERTY layer, along with the right thumb shift or shift on F.

There is also a semicolon at the N position on NUM layer, which can be used with the F position shift.

**Comment by npx** [comment]
Thank you! I like the layout so far. I love the combo idea to free up the symbol layer and have numbers and symbols on one layer. Gives me more options for window management on nav layer!

**Comment by caksoylar** [comment]
Great, I am happy that it was useful as inspiration!
