### ISSUE TITLE
[BUG?] Mouse working only over USB

### ISSUE THREAD

**Issue by paoloantinori** [caksoylar/zmk-config#3]
Hi there!

Over the last week, I've redeployed a layout on my Corneish Zen and started observing a strange behavior that took me a while to track down.
I'm not sure if this is a bug with `zmk` or I might have inadvertently introduced some misconfiguration on my side to cause this, so please take this just as an anomaly more than a confirmed bug. Oh, and ideally this report should be reported on https://github.com/caksoylar/zmk but "Issues" are not enabled there.

I've noticed that `&mmv`, with the same customization as your own `mouse.dtsi`, works only if I'm connected over USB. The moment I unplug the cable, the command stops working.

I've verified this on both:

- `caksoylar/zen-8bit`
- `caksoylar/zen-v1+v2+experimental`

And just to be sure that I wasn't introducing any error with my own config repo, I've just deployed your latest build, https://github.com/caksoylar/zmk-config/actions/runs/6976839309, I can confirm the same behavior appears there.
I can tell for sure that I build I had from 3 weeks ago, was working fine, but I have no idea since when the behavior is broken, since I have a gap in my builds with the most recent broken one, noticed only 3 days ago.

Are you able to confirm this? Any chance this might be controlled by a config variable that I have missed?

thank you

**Comment by paoloantinori** [comment]
uh, ignore me here, please. Pairing the keyboard with a new device I've accidentally discovered that Mouse support over BT was working once again. I've unpaired the kb from my Linux box and repaired and everything is working now!
🙄

**Comment by caksoylar** [comment]
Yes, for future reference enabling the mouse endpoint requires re-pairing with some OS. We added this second paragraph on this page https://zmk.dev/docs/behaviors/mouse-emulation for that, although we should move it into a warning box at some point.
